name: Despliegue a Surge

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Surge
        run: npm install -g surge

      - name: Desplegar en Surge.sh
        run: surge ./ Puro.surge.sh --token ${{ secrets.SURGE_TOKEN }}